@echo off
echo Starting Trace Frontend...
cd /d "%~dp0frontend"
if not exist node_modules (
    echo Installing dependencies...
    call npm install --legacy-peer-deps --ignore-scripts
    echo Installing esbuild platform binaries...
    call npm install @esbuild/win32-x64 --save-optional
)
echo Starting dev server on http://localhost:5173...
call npm run dev
pause

